language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_STATIC_ANALYSIS=0
    - TASK_TESTS_COVERAGE=0

matrix:
  include:
    - php: "7.4"
      env:
        - TASK_STATIC_ANALYSIS=0 # set to 1 to enable static analysis
        - TASK_TESTS_COVERAGE=1

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - |
    if [[ $TASK_TESTS_COVERAGE != 1 ]]; then
      # disable xdebug for performance reasons when code coverage is not needed
      phpenv config-rm xdebug.ini || echo "xdebug is not installed"
    fi

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      pecl install ast
    fi

before_script:
  - php --version
  - composer --version
  # enable code coverage
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
        PHPUNIT_COVERAGE_FLAG="--coverage-clover=coverage.clover"
    fi

script:
  - vendor/bin/phpunit --verbose $PHPUNIT_COVERAGE_FLAG
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      composer phan
    fi
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      cat analysis.txt
    fi

after_script:
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

notifications:
  slack:
    -
      rooms:
        -
          secure: YrT6CbMPjn7urDxERUSdfbyw+HjASOGYCuHWaOmtle+QZmwlDOE5BEFjJREWQqywkgPFj13WNNGgDSWZImRWtbDNGVYpQMoRd6ZOBOce/9Xmaywj8HQk8MpUttiYnxeUUZUlkt6WICdJKLdIeoF6fCnHUjF5cQrhT+Pm2PKV9MKwt810a8C/zmqzH9BQ8tjP7bRm+Y/yvmh8VkZPIi8qtSLYBJ7d9nleuVGkzd2894VSuvupyjMeynvi1xJLiP4BGSr/ofK+I/EXrQI6SjypHoo1gTRNvMbJejsTlwOA8xS2etb7NwJcoA0fc7wcVNvgXlZert8fLbdOSp3bqr/DEeniRhYhBnHFbEXXMxj04Bzu0xP2vJdwY8LAq1TskERheW3cY6QV7tg/T+2+IpNpmiqsWPoholeMyzy974sw6EtAz3E+SP0ss7COJ6naWykI9GhVEtCIesCU5eD5tXm7prftJrgYlfzcP9+Uaaf7xcPvbHYK8xjIbit7twsDrFro8e7/8s2K+8kkWflHvn7iT2NqZz8poRt7KuAZwh2XWx1+5rZOlr1iopgK9hdZNkaHTVeiYJa6qWJtxb71HxR5T/nmlrrku15bXx/fUZ0NTL/QQHtlF/Cm1+Y6DsDpjRND4N27ZJK/IGz7+DcHxGeALFe6IngPtcD9mdS9N+lNctI=
      on_success: always
      on_failure: never
      on_pull_requests: false
    -
      rooms:
        -
          secure: RfAc/JTejBxXv1sjaUML4PahUPjLMAW4vhMFiiuwUEkInlWgxSxVCFsQVNlZFcqin2Kbqbz3lDpXMj8VGuO1pbMeE4LWYyNh9+h7qjo2QydUrd/vcSGEEsdqcknssIuO913laVlNKk123Ze3KkoxTCyLn0avYAXsU5s699wO20Yh7EMcvkN6sIWxCWZtHWN4SgrKjeoQt0ElYxHzh51evx7/UeG+hxbdUeMJPBMNhW9zu0ntuC+C7GZt79CK/YCEyOeGeHEsWT6bCQFC6sqV5JjsxGkrU9c/kOKw8l05EYSMVwxLHR6YwMXmE66p7u+c8j/mR0/Xzo1ONkTw70mzjwxr219/74xi+UQ00cnJN4MDJFQh5spfLEcGFPoD2WakUrhVCSVhI/pH3zaoclobLlNiDy2SP7GCIA7Msi5UG8giS89ux2/ALrfAtzAo34A2/JIbsBFcNZ9+SMh2Rl6arHjDyRSgaDmnre23nG3sOhdzb9Gy/ZsBqa25lM2Alk4qiNqeaI9QyeuoefV1nJgRcTd13rEUwSVMOrdK4IlJntMOaCCt5K9S5fPkPSaUMQnkdMcO1hQ3sicuP7ba6VEiumYOzfsG6I1O+OJZNoXGE0dJPyX27uuu4CsALhgK5QEPQC/IMy40Tg/glIzZYX42Fe5K6w/5NszXqmP4loG2ebU=
      on_success: never
      on_failure: always
      on_pull_requests: false
