on:
  - pull_request
  - push

name: static analysis by phan

jobs:
  mutation:
    name: PHP ${{ matrix.php-version }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php-version:
          - "7.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          tools: cs2pr, phan

      - name: Static analysis by phan
        run: phan --no-progress-bar --output-mode checkstyle | cs2pr --graceful-warnings --colorize
